version: "3.8"
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.back
    image: writer_back:latest
    ports:
      - "20015:3000"
    depends_on:
      - frontend

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.front
    image: writer_front:latest
    ports:
      - "20016:80"
