version: "3.8"
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.back
    image: tutoblockchain_back:latest
    ports:
      - "20017:3000"
    depends_on:
      - frontend

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.front
    image: tutoblockchain_front:latest
    ports:
      - "20018:80"
