version: "3.8"
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.back
    image: thelosttreasure_back:latest
    ports:
      - "20007:3000"
    depends_on:
      - frontend

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.front
    image: thelosttreasure_front:latest
    ports:
      - "20008:80"
