version: "3.8"
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.back
    image: fightoo_back:latest
    ports:
      - "20011:3000"
    depends_on:
      - frontend

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.front
    image: fightoo_front:latest
    ports:
      - "20012:80"
